"""Adicionando estrutura de Familia

Revision ID: 7c8c11d12904
Revises: 8a12e15d989c
Create Date: 2026-07-02 10:15:26.684010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8c11d12904'
down_revision = '8a12e15d989c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('familias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'familias', ['familia_id'], ['id'])

    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'familias', ['familia_id'], ['id'])

    with op.batch_alter_table('faturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'familias', ['familia_id'], ['id'])

    with op.batch_alter_table('meios_pagamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'familias', ['familia_id'], ['id'])

    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'familias', ['familia_id'], ['id'])

    with op.batch_alter_table('movimentacoes_cartao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'familias', ['familia_id'], ['id'])

    with op.batch_alter_table('pagamentos_fatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'familias', ['familia_id'], ['id'])

    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'familias', ['familia_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'familias', ['familia_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('familia_id')

    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('familia_id')

    with op.batch_alter_table('pagamentos_fatura', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('familia_id')

    with op.batch_alter_table('movimentacoes_cartao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('familia_id')

    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('familia_id')

    with op.batch_alter_table('meios_pagamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('familia_id')

    with op.batch_alter_table('faturas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('familia_id')

    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('familia_id')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('familia_id')

    op.drop_table('familias')
    # ### end Alembic commands ###
