"""Adicionando coluna compra_grupo_id

Revision ID: 8a12e15d989c
Revises: 
Create Date: 2026-06-24 22:45:43.166278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a12e15d989c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes_cartao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compra_grupo_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes_cartao', schema=None) as batch_op:
        batch_op.drop_column('compra_grupo_id')

    # ### end Alembic commands ###
