"""Cria tabela OrcamentoMensal

Revision ID: f862d0888b38
Revises: 7c8c11d12904
Create Date: 2026-07-08 12:22:01.513333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f862d0888b38'
down_revision = '7c8c11d12904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamentos_mensais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('meta_poupanca_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['familia_id'], ['familias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('faturas', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('meios_pagamento', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('movimentacoes_cartao', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pagamentos_fatura', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('pagamentos_fatura', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('movimentacoes_cartao', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('meios_pagamento', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('faturas', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('familia_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('orcamentos_mensais')
    # ### end Alembic commands ###
